# Generated by Django 4.1 on 2022-11-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarProduct',
            new_name='CartProduct',
        ),
    ]
